version: 2
updates:
#######################################################
  - package-ecosystem: 'npm'
    directory: '/apps/server'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 25
    versioning-strategy: increase
    allow:
      - dependency-name: "@nestjs/*"
      - dependency-name: "@nestia/*"
      - dependency-name: "nestia"
      - dependency-name: "tstl"
      - dependency-name: "typia"
      - dependency-name: "typescript"
      - dependency-name: "typescript-transform-paths"
      - dependency-name: "ts-patch"
    groups:
      Samchon:
        patterns:
          - "@nestia/*"
          - "nestia"
          - "tstl"
          - "typia"
      NestJS:
        patterns:
          - "@nestjs/*"
      TypeScript:
        patterns:
          - "typescript"
          - "typescript-transform-paths"
          - "ts-patch"
#######################################################
  - package-ecosystem: 'npm'
    directory: '/apps/server/packages/api'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 25
    versioning-strategy: increase
    allow:
      - dependency-name: "@nestia/fetcher"
      - dependency-name: "typia"
      - dependency-name: "tgrid"
    groups:
      Samchon:
        patterns:
          - "@nestia/fetcher"
          - "typia"
          - "tgrid"
#######################################################
  - package-ecosystem: 'npm'
    directory: '/apps/web'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 25
    versioning-strategy: increase
    allow:
      - dependency-name: "vite"
      - dependency-name: "vitest"
      - dependency-name: "vite-tsconfig-paths"
      - dependency-name: "@vitejs/plugin-react"
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "@types/react"
      - dependency-name: "@types/react-dom"
      - dependency-name: "typescript"
    groups:
      Vite:
        patterns:
          - "vite"
          - "vitest"
          - "vite-tsconfig-paths"
          - "@vitejs/plugin-react"
      React:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      Typescript:
        patterns:
          - "typescript"
 